baseurl = "https://hack.bs.it/"
theme = "terminal"
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  enableGitInfo = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "h4ckbs"
  site = "h4ckbs"

[languages]
  [languages.en]
    languageName = "English"
    contentDir = 'content/en'
    title = "hack.bs"
    subtitle = "A space for hackers, designed by hackers"
    owner = ""
    keywords = "hackbs, h4ckbs, hackerspace, bitcoin, cypherpunk, brescia, italy, opensource, freedom, privacy"
    copyright = "hack.bs"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "hack.bs"
      logoHomeLink = "/"

  [languages.it]
    languageName = "Italiano"
    contentDir = 'content/it'
    title = "hack.bs"
    subtitle = "Uno spazio per hacker, inventato da hacker"
    owner = ""
    keywords = "hackbs, h4ckbs, hackerspace, bitcoin, cypherpunk, brescia, italia, opensource, liberta, privacy"
    copyright = "hack.bs"
    menuMore = "Mostra di pi첫"
    readMore = "Leggi di pi첫"
    readOtherPosts = "Leggi altri post"
    newerPosts = "Post pi첫 recenti"
    olderPosts = "Post pi첫 vecchi"
    missingContentMessage = "Pagina non trovata..."
    missingBackButtonLabel = "Torna alla home page"

    [languages.it.params.logo]
      logoText = "hack.bs"
      logoHomeLink = "/it"
